name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.artifact }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ needs.build.outputs.dmg }}
            ${{ needs.build.outputs.zip }}
          generate_release_notes: true
